"""Constants for the cloudflare ai conversation assistant integration."""

DOMAIN = "home-assistant-cloudflare-ai-conversation-agent"
CONF_PROMPT = "prompt"
CONF_MODEL = "model"
CONF_ACCOUNT_ID = "account_id"
CONF_GATEWAY_ID = "gateway_id"
CONF_TOP_P = "top_p"
CONF_TEMPERATURE = "temperature"
CONF_MAX_TOKENS = "max_tokens"
